# Generated by Django 2.2.13 on 2020-12-27 09:54

import common.fields.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0062_auto_20201117_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivilegeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_result', common.fields.model.JsonDictTextField(blank=True, null=True)),
                ('check_status', models.IntegerField(default=0)),
                ('exception_msg', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['parent_key', 'value'], 'verbose_name': 'Node'},
        ),
    ]
